project:
  type: website


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Arvi Puka"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    background: light
    left:
      - "Copyright 2024, Arvi Puka"


